# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).

# crew = Team.create(name: 'CREW', color: '#fff')
# ninjas = Team.create(name: 'Rails Ninjas', color: '#f00')

# Member.create(name: 'stefan', email: 'stefan@example.com', team: crew)
# ninjas = Team.find_by(id: 3)
# Member.create(name: 'peter', email: 'peter@example.com', team: ninjas)
# Member.create(name: 'tove', email: 'tove@example.com', team: ninjas)
# Member.create(name: 'lisa', email: 'lisa@example.com', team: ninjas)
# Member.create(name: 'isak', email: 'isak@example.com', team: ninjas)
# Member.create(name: 'ant', email: 'ant@example.com', team: ninjas)

Item.create(name: 'Antenn', image: 'antenna', cost: 100)
Item.create(name: 'Yxa', image: 'axe', cost: 100)
Item.create(name: 'Batteri', image: 'battery', cost: 100)
Item.create(name: 'Cykel', image: 'bike', cost: 500)
Item.create(name: 'Kikare', image: 'binoculars', cost: 100)
Item.create(name: 'Hink', image: 'bucket', cost: 100)
Item.create(name: 'Kanot', image: 'canoe', cost: 500)
Item.create(name: 'Bil', image: 'car_beetle', cost: 2000)
Item.create(name: 'Kasinomarker 100', image: 'casino_chip_100', cost: 100)
Item.create(name: 'Kasinomarker 1000', image: 'casino_chip_1000', cost: 1000)
Item.create(name: 'Kasinomarker 200', image: 'casino_chip_200', cost: 200)
Item.create(name: 'Kasinomarker 500', image: 'casino_chip_500', cost: 500)
Item.create(name: 'Kristallkula', image: 'crystal_ball', cost: 100)
Item.create(name: 'Piltavla', image: 'dartboard', cost: 100)
Item.create(name: 'Boxerhund', image: 'dog_boxer', cost: 300)
Item.create(name: 'Eld', image: 'fire', cost: 500)
Item.create(name: 'Fiskkrok', image: 'fish_hook', cost: 100)
Item.create(name: 'Ficklampa', image: 'flashlight', cost: 200)
Item.create(name: 'Hammare', image: 'hammer', cost: 100)
Item.create(name: 'Varmkorv', image: 'hot_dog_sandwich', cost: 100)
Item.create(name: 'Stege', image: 'ladder', cost: 300)
Item.create(name: 'Lykta', image: 'lamp_camping', cost: 200)
Item.create(name: 'Bärbar Dator', image: 'laptop_angle', cost: 100)
Item.create(name: 'Magnet', image: 'magnet', cost: 100)
Item.create(name: 'Tändsticksask', image: 'matchbox', cost: 300)
Item.create(name: 'Musfälla', image: 'mouse_trap', cost: 100)
Item.create(name: 'Navigationsenhet', image: 'navigation_device', cost: 300)
Item.create(name: 'Skattkista', image: 'pirate_treasure_box', cost: 500)
Item.create(name: 'Tång', image: 'pliers', cost: 100)
Item.create(name: 'Fickkniv', image: 'pocket_knife', cost: 100)
Item.create(name: 'Kanin', image: 'rabbit', cost: 200)
Item.create(name: 'Säck', image: 'sack', cost: 100)
Item.create(name: 'Säkerhetsnål', image: 'safety_pin', cost: 50)
Item.create(name: 'Såg', image: 'saw', cost: 100)
Item.create(name: 'Vespa', image: 'scooter_vespa', cost: 1000)
Item.create(name: 'Skruvmejsel', image: 'screwdriver', cost: 100)
Item.create(name: 'Får', image: 'sheep', cost: 300)
Item.create(name: 'Spade', image: 'shovel', cost: 100)
Item.create(name: 'Sovsäck', image: 'sleeping_bag', cost: 100)
Item.create(name: 'Snorkel', image: 'snorkel_mask', cost: 100)
Item.create(name: 'Mobiltelefon', image: 'telephone_mobile', cost: 1000)
Item.create(name: 'Tält', image: 'tent', cost: 500)
Item.create(name: 'Klocka', image: 'watch', cost: 100)
